language: php

install: composer update --dev
script: ./vendor/bin/phpunit

jobs:
  include:
    - stage: Unit tests
      php: 7.2
    - stage: Unit tests
      php: 7.3
    - stage: Unit tests
      php: 7.4
